### ISSUE TITLE
Correções a fazer

### ISSUE THREAD

**Issue by nmaia19** [nmaia19/se_liga_hein#70]
- [x] Corrigir versionamento do código
- [x]  Criar novas branchs de correção
- [x] Adicionar detalhes do css (transições, ajustes de posicionamento)
- [x] Corrigir bugs do css
- [x] Dropdown do minha área precisa aparecer só quando tiver logado
- [x] Ajustar select da página search

**Comment by cruzpyu** [comment]
ihuuu
